import com.XploR.drools.OrderRequest;
import com.XploR.drools.CustomerType;
global com.XploR.drools.OrderDiscount orderDiscount;

dialect "mvel"

rule "Age based discount"
    when
        OrderRequest(age < 20 || age > 50)
    then
        orderDiscount.setDiscount(orderDiscount.getDiscount() + 10);
end

rule "Customer type based discount - Loyal customer"
    when
        OrderRequest(customerType.getValue == "LOYAL")
    then
        orderDiscount.setDiscount(orderDiscount.getDiscount() + 5);
end

rule "Customer type based discount - others"
    when
        OrderRequest(customerType.getValue != "LOYAL")
    then
        orderDiscount.setDiscount(orderDiscount.getDiscount() + 3);
end

rule "Amount based discount"
    when
        OrderRequest(amount > 1000L)
    then
        orderDiscount.setDiscount(orderDiscount.getDiscount() + 5);
end

rule "New customer discount"
    when
       OrderRequest(customerType.getValue() == "NEW")
    then
        orderDiscount.setDiscount(50);
end